apiVersion: "v1"
kind: "Service"
metadata:
  name: "{APPNAME}-service"
  namespace: "royal"
  labels:
    app: "{APPNAME}"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
  selector:
    app: "{APPNAME}"
  type: "ClusterIP"
